name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Change gradlew permissions
        run: chmod +x backend/gradlew  # gradlew 실행 권한 추가

      - name: Build Backend
        run: |
          cd backend
          ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Docker Username
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      - name: Build and Push Docker Image
        run: |
          cd backend
          DOCKER_USER=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')  # 대문자가 포함되어 있으면 소문자로 변환
          docker build -t sicksick-backend .
          docker push sicksick-backend
